#!/usr/bin/env python
'''
srvinv-cli/scripts/inventory_this
a script to register this machine inside the srvinv
this is very basic and relies on some assumptions (e.g. disksize is only '/')
'''
import sys
sys.path.append("..")
import libsrvinv
import psutil
import netifaces
import json
import platform
import string
from netaddr import IPNetwork, IPAddress

cpu_cores = str(psutil.cpu_count())
ram_size_mb = str(psutil.virtual_memory().total / 1024 / 1024)
disk_size_gb = str(psutil.disk_usage('/').total / 1024 / 1024 / 1024)

interfaces = netifaces.interfaces()
interfaces_to_inv = []
for interface in interfaces:
  addrs = netifaces.ifaddresses(interface)
  interfaces_to_inv.append({interface: addrs})

# set net by finding the network (has to be predefined)
net_id = None
networks = libsrvinv.search('net', 'name', '*')

priv_ip = ''
priv_interface = ''
for net in networks:
  if 'netmask' in net:
    for interface in interfaces:
      if not interface == 'lo':
        addrs = netifaces.ifaddresses(interface)
        if netifaces.AF_INET in addrs:
          ips = addrs[netifaces.AF_INET]
          for ip in ips:
            if not ip['addr'] == '127.0.0.1':
              if IPAddress(str(ip['addr'])) in IPNetwork(net['netmask']):
                priv_ip = str(ip['addr'])
                priv_interface = interface
                net_id = net['name']
                break
interfaces_to_inv = json.dumps(interfaces_to_inv)

if not priv_ip:
  print('Failed to match local IPs against registered networks')
  sys.exit(1)

srvid = 'srv{:03d}{:03d}'.format(*[int(x) for x in priv_ip.split('.')[2:]])

os = platform.system()
os_version = platform.release()
os_arch = platform.machine()

print('Inventory srvid: ' + srvid)
# try to register the srvid
if libsrvinv.register('srv', srvid) != 2: print('Register: done')
# set values
if libsrvinv.set('srv', srvid, 'net_id', net_id) == 0: print('net_id: ' + net_id)
if libsrvinv.set('srv', srvid, 'cpu_cores', cpu_cores) == 0: print('CPU cores: ' + cpu_cores)
if libsrvinv.set('srv', srvid, 'ram_size_mb', ram_size_mb) == 0: print('RAM size mb: ' + ram_size_mb)
if libsrvinv.set('srv', srvid, 'disk_size_gb', disk_size_gb) == 0: print('disk size gb: ' + disk_size_gb)
if libsrvinv.set('srv', srvid, 'interfaces', interfaces_to_inv) == 0: print('interfaces: ' + interfaces_to_inv)
if libsrvinv.set('srv', srvid, 'os', os) == 0: print('os: ' + os)
if libsrvinv.set('srv', srvid, 'os_version', os_version) == 0: print('os version: ' + os_version)
if libsrvinv.set('srv', srvid, 'os_arch', os_arch) == 0: print('os arch: ' + os_arch)
if libsrvinv.set('srv', srvid, 'priv_ip', priv_ip) == 0: print('priv ip: ' + priv_ip)
if libsrvinv.set('srv', srvid, 'priv_interface', priv_interface) == 0: print('priv interface: ' + priv_interface)
